User profile page
comp426-2023-spring/a99-bettercat pull request #22
Opened 2023-04-26 00:03 UTC by muktha-s

made a list of the user's favorite restaurants and favorite categories appear on the front end

2023-04-26 00:11 UTC, aayush110 commented
LGTM Muktha! I can create another PR and further tweak this. But as of now, I think we can merge!

2023-04-26 00:18 UTC, ajaygandecha requested changes
Just adding a comment here to restore the previous documentation before we merge - otherwise, looks great!

2023-04-26 00:18 UTC, ajaygandecha commented on pages/index.tsx
>  export async function getStaticProps() {
I would re-add this deleted documentation!

2023-04-26 00:20 UTC, ajaygandecha commented on pages/index.tsx
>  export async function getStaticProps() {
Maybe edit the `index` part to `user/[id]` so that the documentation is accurate!

2023-04-26 00:39 UTC, ajaygandecha approved these changes
LGTM! Ready to merge.

2023-04-27 21:32 UTC, ajaygandecha commented
Let me know when this needs a re-review @aayush110 and @muktha-s .

2023-05-05 13:59 UTC, merged